#! /usr/bin/env bash

__p4_ps1() { return; }
which p4 > /dev/null
[[ $? -ne 0 || -z $P4_USER ]] && return

export P4PS_BRANCH_LEVEL=2
export P4PS_ROOT=$(p4 info | grep 'Client root: ' | cut -d' ' -f 3)

__p4_ps1()
{
    local cwd=$(pwd)
    if [[ $cwd =~ $P4PS_ROOT ]]; then
	local branch=$(p4 where | cut -d/ -f $(( 2 + $P4PS_BRANCH_LEVEL )))
	if [[ ! $branch =~ "..." && ! $branch = $(basename $cwd) ]]; then
	    printf "%s" $branch
	fi
    else
	printf ""
    fi
}
