#!/usr/bin/env bash

__jobs() {
	local jobs=$(jobs | wc -l | cut -d ' ' -f 8)
	[[ $jobs != 0 ]] && {
	   echo -en "|\033[00;33m${jobs}\033[00m|"
	}
}

export ALTERNATE_EDITOR=""
export VISUAL=emacsclient
export EDITOR=emacsclient
