#! /usr/bin/env bash

[[ $# != 2 ]] && echo "usage: $(basename ${0%.*}) <file> <extension>" && exit 1

OLDFILE=$1
NEWEXTN=.$2

[[ ! -f $OLDFILE ]] && echo "file '$OLDFILE' does not exist" && exit 1

NOEXTN=${OLDFILE%.*}
# allow an extension to be removed with '-'
[[ "$NEWEXTN" = ".-" ]] && unset NEWEXTN
NEWFILE=${NOEXTN}${NEWEXTN}

[[ -f "$NEWFILE" ]] && echo "file '$NEWFILE' already exists" && exit 1

mv "$OLDFILE" "$NEWFILE"
