#!/usr/bin/env bash

usage()
{
    echo -e "Usage: ${0/\.\//} [option] <filename>\n\nOPTIONS:\n\t--print\t\toutput variables to the given file"
    exit
}

[[ ! -z $1 ]] && [[ -z $2 ]] && usage

for i in {0..255} ; do
    printf "\x1b[38;5;${i}mcolour${i}\n"
done
