#! /usr/bin/env bash
# Report duplicate files in a directory.

declare -i COUNT
declare -a EXCLUDES
NAME=$(basename $0)
USAGE="USAGE: $NAME [hvx] <ARGUMENTS>"
HELP="\t-h\tdisplay help\n\t-v\tdisplay version\n\t-x\texclude extension(s)"
VERSION=1

while getopts ":hvx:" opt; do
    case $opt in
	h) echo "$USAGE && echo -e $HELP" ; exit 0 ;;
	v) echo "$NAME version $VERSION"; exit 0 ;;
	x) EXCLUDES=$OPTARG ;;
	\?) echo -e "Unrecognised option: -$OPTARG\n$USAGE" ; exit 1 ;;
    esac
done

COUNT=0
for NEXT in *; do
    [[ -z $LAST ]] && { LAST=$NEXT; continue; }
    FNOEXT="${NEXT%.*}"
    FEXT=${NEXT##*.}
    IS_EXCLD=false
    for EXCLUDE in ${EXCLUDES[@]}; do
	[[ ${EXCLUDES[@]/$FEXT} != ${EXCLUDES[@]} ]] && {
	    IS_EXCLD=true; break
	}
    done
    [[ $IS_EXCLD == true ]] && continue
    [[ ${LAST%.*} == $FNOEXT ]] && {
	echo $NEXT is a duplicate of $LAST; COUNT+=1
    } || {
	LAST=$NEXT
    }
done
[[ $COUNT -eq 0 ]] && {
    echo "$NAME: no duplicates found" 
}||{
    echo -n "$NAME: found $COUNT duplicate"
    [[ $COUNT -gt 1 ]] && {
	echo "s" 
    }||{
	echo
    }
}
