# If not running interactively, don't do anything
[ -z "$PS1" ] && return

CCD=$([ -h ~/.bash_profile ] && {
    _d=$(dirname $(readlink ~/.bash_profile))
    [[ $_d =~ etc$ ]] && echo ${_d/\/etc/} || echo $_d
} || {
    # we're probably in serious trouble here, but let's try
    echo ~/
})


source $CCD/libexec/_functions
# files in libexec provide functions for lazy loading
for file in $CCD/libexec/*.bash; do
    load $file
done

unset PATH

include aliases
include darwin
include golang
include homebrew
include java
#include man_path
include ocaml
include path
include prompt
include python
include rust
#include ranger

include completions/diskutil_completion
include completions/git_completion
include completions/pass_completion
include completions/rust_completion
include completions/docker
include completions/docker-machine


unset CCD
